runtime: python313

handlers:
  - url: /static/game/serpent-fusion.wasm
    static_files: static/game/serpent-fusion.wasm
    upload: static/game/serpent-fusion.wasm
    mime_type: application/wasm
    http_headers:
      Vary: Accept-Encoding
      Cache-Control: "public, max-age=31536000"

  - url: /static
    static_dir: static

  - url: /.*
    script: auto

automatic_scaling:
  max_instances: 1